// flow-typed signature: 38ce8d8c7fb1d85751e89647461345e9
// flow-typed version: <<STUB>>/flow-cli_v^0.0.0-pre/flow_v0.76.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'flow-cli'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'flow-cli' {
  declare module.exports: any;
}
