// @flow strict

export type Entry = {
  name: string,
  symbol: string,
  sector: string,
}

export const FTSE100: Array<Entry> = [
  {name: "3i", symbol: "III", sector: "Financial Services"},
  {name: "Admiral Group", symbol: "ADM", sector: "Nonlife Insurance"},
  {name: "Anglo American plc", symbol: "AAL", sector: "Mining"},
  {name: "Antofagasta", symbol: "ANTO", sector: "Mining"},
  {name: "Ashtead Group", symbol: "AHT", sector: "Support Services"},
  {name: "Associated British Foods", symbol: "ABF", sector: "Food Producers"},
  {name: "AstraZeneca", symbol: "AZN", sector: "Pharmaceuticals & Biotechnology"},
  {name: "Aviva", symbol: "AV.", sector: "Life Insurance"},
  {name: "BAE Systems", symbol: "BA.", sector: "Aerospace & Defence"},
  {name: "Barclays", symbol: "BARC", sector: "Banks"},
  {name: "Barratt Developments", symbol: "BDEV", sector: "Household Goods & Home Construction"},
  {name: "Berkeley Group Holdings", symbol: "BKG", sector: "Household Goods & Home Construction"},
  {name: "BHP", symbol: "BLT", sector: "Mining"},
  {name: "BP", symbol: "BP.", sector: "Oil & Gas Producers"},
  {name: "British American Tobacco", symbol: "BATS", sector: "Tobacco"},
  {name: "British Land", symbol: "BLND", sector: "Real Estate Investment Trusts"},
  {name: "BT Group", symbol: "BT.A", sector: "Fixed Line Telecommunications"},
  {name: "Bunzl", symbol: "BNZL", sector: "Support Services"},
  {name: "Burberry", symbol: "BRBY", sector: "Personal Goods"},
  {name: "Carnival Corporation & plc", symbol: "CCL", sector: "Travel & Leisure"},
  {name: "Centrica", symbol: "CNA", sector: "Gas, Water & Multi-utilities"},
  {name: "Coca-Cola HBC AG", symbol: "CCH", sector: "Beverages"},
  {name: "Compass Group", symbol: "CPG", sector: "Support Services"},
  {name: "CRH plc", symbol: "CRH", sector: "Construction & Materials"},
  {name: "Croda International", symbol: "CRDA", sector: "Chemicals"},
  {name: "DCC plc", symbol: "DCC", sector: "Support Services"},
  {name: "Diageo", symbol: "DGE", sector: "Beverages"},
  {name: "Direct Line Group", symbol: "DLG", sector: "Non-life Insurance"},
  {name: "easyJet", symbol: "EZJ", sector: "Travel & Leisure"},
  {name: "Evraz", symbol: "EVR", sector: "Industrial Metals & Mining"},
  {name: "Experian", symbol: "EXPN", sector: "Support Services"},
  {name: "Ferguson plc", symbol: "FERG", sector: "Support Services"},
  {name: "Fresnillo plc", symbol: "FRES", sector: "Mining"},
  {name: "GlaxoSmithKline", symbol: "GSK", sector: "Pharmaceuticals & Biotechnology"},
  {name: "Glencore", symbol: "GLEN", sector: "Mining"},
  {name: "GVC Holdings", symbol: "GVC", sector: "Travel & Leisure"},
  {name: "Halma", symbol: "HLMA", sector: "Electronic & Electrical Equipment"},
  {name: "Hargreaves Lansdown", symbol: "HL.", sector: "Financial Services"},
  {name: "HSBC", symbol: "HSBA", sector: "Banks"},
  {name: "Imperial Brands", symbol: "IMB", sector: "Tobacco"},
  {name: "Informa", symbol: "INF", sector: "Media"},
  {name: "InterContinental Hotels Group", symbol: "IHG", sector: "Travel & Leisure"},
  {name: "International Airlines Group", symbol: "IAG", sector: "Travel & Leisure"},
  {name: "Intertek", symbol: "ITRK", sector: "Support Services"},
  {name: "ITV plc", symbol: "ITV", sector: "Media"},
  {name: "Johnson Matthey", symbol: "JMAT", sector: "Chemicals"},
  {name: "Just Eat", symbol: "JE.", sector: "General Retailers"},
  {name: "Kingfisher plc", symbol: "KGF", sector: "General Retailers"},
  {name: "Land Securities", symbol: "LAND", sector: "Real Estate Investment Trusts"},
  {name: "Legal & General", symbol: "LGEN", sector: "Life Insurance"},
  {name: "Lloyds Banking Group", symbol: "LLOY", sector: "Banks"},
  {name: "London Stock Exchange Group", sector: "LSE", symbol: "Financial Services"},
  {name: "Marks & Spencer", symbol: "MKS", sector: "General Retailers"},
  {name: "Melrose Industries", symbol: "MRO", sector: "Automobiles & Parts"},
  {name: "Micro Focus", symbol: "MCRO", sector: "Software & Computer Services"},
  {name: "Mondi", symbol: "MNDI", sector: "Forestry & Paper"},
  {name: "Morrisons", symbol: "MRW", sector: "Food & Drug Retailers"},
  {name: "National Grid plc", symbol: "NG.", sector: "Gas, Water & Multi-utilities"},
  {name: "Next plc", symbol: "NXT", sector: "General Retailers"},
  {name: "NMC Health", symbol: "NMC", sector: "Health Care Equipment & Services"},
  {name: "Ocado", symbol: "OCDO", sector: "Food & Drug Retailers"},
  {name: "Paddy Power Betfair", symbol: "PPB", sector: "Travel & Leisure"},
  {name: "Pearson plc", symbol: "PSON", sector: "Media"},
  {name: "Persimmon plc", symbol: "PSN", sector: "Household Goods & Home Construction"},
  {name: "Prudential plc", symbol: "PRU", sector: "Life Insurance"},
  {name: "Randgold Resources", symbol: "RRS", sector: "Mining"},
  {name: "Reckitt Benckiser", symbol: "RB.", sector: "Household Goods & Home Construction"},
  {name: "RELX Group", symbol: "REL", sector: "Media"},
  {name: "Rentokil Initial", symbol: "RTO", sector: "Support Services"},
  {name: "Rio Tinto Group", symbol: "RIO", sector: "Mining"},
  {name: "Rightmove", symbol: "RMV", sector: "Media"},
  {name: "Rolls-Royce Holdings", symbol: "RR.", sector: "Aerospace & Defence"},
  {name: "Royal Bank of Scotland Group", symbol: "RBS", sector: "Banks"},
  {name: "Royal Dutch Shell", symbol: "RDSA", sector: "Oil & Gas Producers"},
  {name: "Royal Mail", symbol: "RMG", sector: "Industrial transportation"},
  {name: "RSA Insurance Group", symbol: "RSA", sector: "Nonlife Insurance"},
  {name: "Sage Group", symbol: "SGE", sector: "Software & Computer Services"},
  {name: "Sainsbury's", symbol: "SBRY", sector: "Food & Drug Retailers"},
  {name: "Schroders", symbol: "SDR", sector: "Financial Services"},
  {name: "Scottish Mortgage Investment Trust", symbol: "SMT", sector: "Equity Investment Instruments"},
  {name: "Segro", symbol: "SGRO", sector: "Real Estate Investment Trusts"},
  {name: "Severn Trent", symbol: "SVT", sector: "Gas, Water & Multi-utilities"},
  {name: "Shire plc", symbol: "SHP", sector: "Pharmaceuticals & Biotechnology"},
  {name: "Sky plc", symbol: "SKY", sector: "Media"},
  {name: "Smith & Nephew", symbol: "SN.", sector: "Health Care Equipment & Services"},
  {name: "Smith, D.S.", symbol: "SMDS", sector: "General Industrials"},
  {name: "Smiths Group", symbol: "SMIN", sector: "General Industrials"},
  {name: "Smurfit Kappa", symbol: "SKG", sector: "General Industrials"},
  {name: "SSE plc", symbol: "SSE", sector: "Electricity"},
  {name: "Standard Chartered", symbol: "STAN", sector: "Banks"},
  {name: "Standard Life Aberdeen", symbol: "SLA", sector: "Financial Services"},
  {name: "St. James's Place plc", symbol: "STJ", sector: "Life Insurance"},
  {name: "Taylor Wimpey", symbol: "TW.", sector: "Household Goods & Home Construction"},
  {name: "Tesco", symbol: "TSCO", sector: "Food & Drug Retailers"},
  {name: "TUI Group", symbol: "TUI", sector: "Travel & Leisure"},
  {name: "Unilever", symbol: "ULVR", sector: "Personal Goods"},
  {name: "United Utilities", symbol: "UU.", sector: "Gas, Water & Multi-utilities"},
  {name: "Vodafone Group", symbol: "VOD", sector: "Mobile Telecommunications"},
  {name: "Whitbread", symbol: "WTB", sector: "Retail hospitality"},
  {name: "WPP plc", symbol: "WPP", sector: "Media"},
]

export const FTSE100Names: Array<string> = FTSE100.map(x => x.name)

export const FTSE100Symbols: Array<string> = FTSE100.map(x => x.symbol)
